RANDOM_SEED = 42
MAX_FITNESS = 0
NULL_FITNESS = 1

IMAGE_THRESHOLD_VALUE = 127
DEFAULT_DATASET = "Datasets/dataset/"
DEFAULT_DATASET_ADVANCED = "Datasets/written_hiragana_dataset/"

POPULATION_SIZE = 100
MAX_GENERATIONS = 100
TOURNAMENT_SIZE = 2
MUTATION_INCREASE_STEP = 1

DEBUG_PRINT = False
